version: '3'

services:
  server:
    image: registry.gitlab.ic.unicamp.br/edson/data_collection_server:4.0
    ports:
      - 8080:8080
      - 7998:7998
    volumes:
      - ./files/pre:/pre_dataset
      - ./files/post:/post_dataset
      - type: bind
        source: ./files/logs/post
        target: /usr/src/h-iaac/captureX/postprocessor/logs
        read_only: false
        bind:
          create_host_path: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=America/Sao_Paulo
      
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

